GET http://localhost:3030/ HTTP/1.1

###

GET http://localhost:3030/things HTTP/1.1

###

GET http://localhost:3030/things/power4 HTTP/1.1

###

GET http://localhost:3030/things/power3/attributes HTTP/1.1

###

GET http://localhost:3030/things/power3/features HTTP/1.1

###

POST http://localhost:3030/things/power4 HTTP/1.1
content-type: application/json

{
    "attributes": {
      "fgrgd": "20kw",
      "label": "Energy Cabin"
    },
    "features": {
      "equipmentRel": {
        "equipment_net9": {
          "equipping": "power4",
          "equipped": "polo_ludovici_a"
        },
        "equipment_net9-1": {
          "equipping": "power4",
          "equipped": "polo_ludovici_b"
        }
      },
      "power": {
        "power-2": {
          "powering": "power4",
          "powered": "gw1"
        }
      }
    }
  }

###

POST http://localhost:3030/things/power2 HTTP/1.1
content-type: application/json

{
    "thingId": "power2",
    "attributes": {
      "capacity": "20kw",
      "category":"equipment",
      "label": "Energy Cabin",
      "typology": "energy_cabin"
    },
    "features": {
      "equipmentRel": {
        "equipment_net9": {
          "equipping": "power2",
          "equipped": "polo_ludovici_a"
        },
        "equipment_net9-1": {
          "equipping": "power2",
          "equipped": "polo_ludovici_b"
        }
      },
      "power": {
        "power-2": {
          "powering": "power2",
          "powered": "gw1"
        }
      }
    }
  }

###

PATCH http://localhost:3030/things/camerino/attributes HTTP/1.1
content-type: application/json

{
  "attributes": {
    "label": "Camerino",
    "typology":"city"
    }
}